### ISSUE TITLE
Can not install pycocotools

### ISSUE THREAD

**Issue by estkae** [Abonia1/Context-Based-LLMChatbot#5]
after run the requestfile i have this issue:
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects
macos 12.6.5
Python 3.7.6

**Comment by estkae** [comment]
pip Uninstall pdfminer
pip install pdfminer.six
brew install poppler
then it should work

**Comment by Abonia1** [comment]
Closing the thread as it was already fixed!
